version: "3"

services:
  spring:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pin-api
    network_mode: "host"
    #    restart: on-failure
    ports:
      - "8080:8080"
    env_file:
      - .env

